apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vishal8docker2026/library-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/library
        - name: PORT
          value: "3000"