version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: library-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: library-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library
    depends_on:
      - mongodb

volumes:
  mongo-data: